create table if not exists competitor.track_barcodes
(
    competitor_name varchar(200),
    barcode         varchar(50),
    primary keep (competitor_name, barcode)
);


create table if not exists competitor.product_sku
(
    competitor_name varchar(200),
    sku             integer,
    barcode         varchar(50)
);

create unique index if not exists competitor.product_sku_sku_competitor_name_barcode_uindex
    on competitor.product_sku (competitor_name, sku, barcode);

create table competitor.products
(
    id           integer primary key generated by default as identity ,
    product_id   integer,
    product_name varchar(500),
    product_url  varchar(500),
    barcode      varchar(200),
    price_max    numeric(22, 2),
    price_min    numeric(22, 2),
    dt_tm        timestamp with time zone default CURRENT_TIMESTAMP not null,
    uuid         uuid                                               not null,
    store_id     integer,
    dt           date                     default CURRENT_DATE      not null
);


create unique index competitors_products_uuid_uindex
    on competitor.products (uuid);

create index competitors_products_dt_idx
    on competitor.products (dt_tm);

create unique index competitors_products_store_id_product_name_product_id_barco_idx
    on competitor.products (store_id, product_name, product_id, barcode, dt);
